name: Build and Push Cybrid Backend Image

on:
  push:
    branches:
      - 'main'
    paths:
      - '**cybrid-backend**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "${{ github.repository }}/cybrid-backend"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Commit SHA
        id: commit
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - id: meta
        run: echo "tags=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.commit.outputs.sha }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest" >> $GITHUB_OUTPUT
          echo "${{ steps.meta.outputs.tags }}"

     
      - name: Committing Tags
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: | 
          echo $TAGS
          echo $TAGS >> $GITHUB_STEP_SUMMARY
