name: Build and Deploy Services

on:
  push: 
    branches: ['devops']
    paths:
      - 'cybrid-backend/**'  
      - 'cybrid-txn/**'  


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 

      # Determine which services to build and deploy
      - name: Set services to build
        id: set_services
        run: |
          echo "CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)" >> $GITHUB_ENV
          if echo "$CHANGED_FILES" | grep -q '^cybrid-backend/'; then
            echo "cybrid-backend=true" >> $GITHUB_ENV
          fi
          if echo "$CHANGED_FILES" | grep -q '^cybrid-txn/'; then
            echo "cybrid-txn=true" >> $GITHUB_ENV
          fi
      - name: github commits 
        run: echo "${{ steps.set_service.outputs.CHANGED_FILES }}"

    
      # Log in to Docker Hub (or private registry)
     
      # Conditionally build and deploy service1
      - name: Build and deploy cybrid Backend 
        if: env.cybrid-backend == 'true'
        run: echo "cybrid Backend service"
       
      # Conditionally build and deploy service2
      - name: Build and deploy cybrid txn
        if: env.cybrid-txn == 'true'
        run: echo "cybrid txn service"

          
