# .github/workflows/detect-changes.yml
name: Detect Changed Glue Job Files

on:
  push:
    branches:
      - main
    paths:
      - 'glue_jobs/*.py'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Show changed files
        run: |
          echo "Changed files in glue_jobs/:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^glue_jobs/.*\.py$' || echo "No changes detected."
