name: Build and Deploy Dev Cosigner Service Image

on:
  push:
    branches:
      - 'main'
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "${{ github.repository }}/goimagetest"
  
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Commit SHA
        id: commit
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - id: meta
        run: |
          echo "tag=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.commit.outputs.sha }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest" >> $GITHUB_OUTPUT
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'

      - name: Verify Go version
        run: go version

      - name: Build and Push Docker Image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: ./goproject
          file: ./goproject/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tag }}

      - name: Committing Tags
        env:
          TAGS: ${{ steps.meta.outputs.tag }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: |
          echo $TAGS
          echo $TAGS >> $GITHUB_STEP_SUMMARY
